### ISSUE TITLE
Deleting a Part with an open toolbox flyout breaks the toolbox UI 

### ISSUE THREAD

**Issue by keithclark** [KanoComponents/kwc-blockly#66]
In the Kano Code editor, when deleting a Part from the Parts list, it's also removed from the toolbox (left sidebar). If the Part being removed is also the current toolbox selection (it's flyout menu is visible), the part is removed from the toolbox but the flyout is left in the sidebar. This leaves the entire sidebar unusable.

Attached is a screengrab of a "Text" part removed from the editor. Note how the flyout is still visible:

![Screen Shot 2020-01-12 at 16 12 48](https://user-images.githubusercontent.com/588665/72221868-76835700-3556-11ea-8ced-41d0353cc833.png)

**Comment by pazdera** [comment]
Thanks for the fix, @keithclark! It's been released in [v3.1.10](https://www.npmjs.com/package/@kano/kwc-blockly).
